current_version: "0.7.0"
strategy:
  name: "semver"
  part: "minor"
commit:
  author: "Jill San Luis <jill.devs@gmail.com>"
tag:
  apply: True
  format: "{version}"
auto_remote_push: True
tracked_files:
  - setup.py